database:
  host: 127.0.0.1
  port: 3306
  username: root
  password: root
  dbName: mmorpg

server:
  ip: 127.0.0.1
  port: 6666
  # 工作线程数
  workerCount: 2
  #AOI视野距离(米)
  aoiViewArea: 50
  #逻辑处理频率(hz)
  updateHz: 50